name: sameep
channels:
  - conda-forge
  - bioconda
dependencies:
  # Python
  - requests=2.31.0
  - pandas=2.1.4
  - certifi=2025.1.31
  # R
  - r-base=4.4.2
  - r-doparallel=1.0.17
  - r-ggiraph=0.8.12
  - r-ggtext=0.1.2
  - r-metrics=0.1.4
  # - r-plotly=4.10.1
  - r-randomforest=4.7_1.1
  - r-ranger=0.17.0
  - r-showtext=0.9_7
  - r-terra=1.8_29
  - r-tidymodels=1.3.0
  - r-tidyverse=2.0.0
  # Snakemake
  - snakemake=7.18.2
  - graphviz=9.0.0
  - quarto=1.6.41
