name: sameep
channels:
  - conda-forge
  - bioconda
dependencies:
  # Python
  - requests=2.31.0
  - pandas=2.1.4
  - certifi=2023.11.17
  # R
  - r-base=4.2.3
  - r-doparallel=1.0.17
  - r-ggiraph=0.8.7
  - r-ggtext=0.1.2
  - r-metrics=0.1.4
  # - r-plotly=4.10.1
  - r-randomforest=4.7_1.1
  - r-ranger=0.14.1
  - r-showtext=0.9_5
  - r-terra=1.7_29
  - r-tidymodels=1.0.0
  - r-tidyverse=1.3.2
  # Snakemake
  - snakemake=7.18.2
  - graphviz=6.0.1
